sudo systemctl stop drone_api.service
sudo systemctl stop drone_camera.service
sudo systemctl stop drone_failsafe.service
sudo systemctl stop drone_find_usb_devices.service
sudo systemctl stop drone_height_sensor.service
sudo systemctl stop drone_lidar.service
sudo systemctl stop drone_positionchanger.service
sudo systemctl stop drone_px4_connection.service
sudo systemctl stop drone_relais.service
sudo systemctl stop drone_status.service
