# bitmask for control:
# bit 0: actuator
# bit 1: body rate
# bit 2: attitude
# bit 3: acceleration
# bit 4: velocity
# bit 5: position

# used control modes:
# 4: attitude and thrust
# 16: velocity
# 32: position
int32 control # control bitmask
---
bool success # if operation succeeded